# Generated by Django 6.0.4 on 2026-05-01 04:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRecord',
            fields=[
                ('match_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'match_record',
            },
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='player_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nickname', models.CharField(max_length=50)),
                ('total_score', models.IntegerField(default=0)),
                ('win_rate', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'player_profile',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.IntegerField(choices=[(0, 'Waiting'), (1, 'Playing'), (2, 'Full')], default=0)),
                ('room_password', models.CharField(blank=True, max_length=128)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='MatchParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_rank', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('score_change', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_participations', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='game.matchrecord')),
            ],
            options={
                'db_table': 'match_participant',
                'constraints': [models.UniqueConstraint(fields=('match', 'user'), name='unique_match_participant'), models.UniqueConstraint(fields=('match', 'player_rank'), name='unique_match_player_rank')],
            },
        ),
    ]
